// Style Transfer Filter Constants
// Used when app is in "Styles" mode for artistic image transformations

export interface StyleFilter {
  id: string;
  name: string;
  prompt: string;
}

export interface StyleFilterCategory {
  id: string;
  name: string;
  icon: string; // Emoji for simplicity in prototype
  filters: StyleFilter[];
}

// Global guidance for style transfer (preserves facial identity)
export const STYLE_TRANSFER_CONSTRAINTS = 
  'CRITICAL IDENTITY PRESERVATION RULES - HIGHEST PRIORITY:\n' +
  '1. FACIAL STRUCTURE: Preserve exact facial bone structure, face shape, jawline, chin shape, cheekbones, and forehead. The person MUST remain 100% recognizable.\n' +
  '2. FACIAL FEATURES: Keep identical eye shape, eye spacing, nose shape, nose bridge, mouth shape, lip proportions, and ear placement. Do NOT alter any facial measurements or proportions.\n' +
  '3. BODY & POSE: Maintain exact body position, pose, posture, limb placement, and overall composition. Do NOT change body proportions or positioning.\n' +
  '4. LIKENESS: The subject must be instantly recognizable as the same person. Preserve their unique facial characteristics and identity completely.\n' +
  '5. STYLE APPLICATION: Apply ONLY the artistic rendering style (brushstrokes, colors, textures, lighting effects). Change styling elements like hair texture, makeup, or clothing texture ONLY - never the underlying anatomy.\n' +
  '6. WHAT TO PRESERVE: Face geometry, facial proportions, body structure, pose, composition, spatial relationships, background layout.\n' +
  '7. WHAT TO CHANGE: Only the artistic medium, rendering technique, color palette, lighting style, and surface textures according to the chosen art style.\n' +
  '\nApply the artistic style as a visual filter over the existing image while keeping all structural elements identical.';

export const STYLE_FILTER_CATEGORIES: StyleFilterCategory[] = [
  {
    id: 'artistic',
    name: 'Artistic',
    icon: '🎨',
    filters: [
      { id: 'anime', name: 'Anime', prompt: 'Apply anime illustration style rendering to this image. PRESERVE: Exact facial structure, face shape, eye shape, nose shape, mouth shape, all facial proportions, body pose, and composition. STYLE: Traditional 2D anime cel-shading with clean linework, solid color blocks, and soft shadows. Render the existing features in anime aesthetic without altering facial geometry or proportions. Keep the person 100% recognizable with their unique facial characteristics intact. Only change the rendering style to anime illustration technique.' },
      { id: 'anime_v2', name: 'Anime Enhanced', prompt: 'Apply cinematic anime key visual rendering style. PRESERVE: Exact facial structure, all facial features, eye shape, nose shape, mouth proportions, face geometry, body pose, clothing design, and composition. STYLE: Refined cel-shading with soft rim lighting and atmospheric gradients. Render existing features with anime aesthetic while maintaining perfect facial likeness. LIGHTING: Dramatic yet balanced with colored highlights. COLOR: Rich, vibrant anime palette. Keep the person 100% recognizable with all unique facial characteristics intact. Only apply anime rendering technique to existing structure.' },
      { id: 'anime_v3', name: 'Anime Cinematic', prompt: 'Apply cinematic anime film rendering style. PRESERVE: Exact facial structure, all facial features, face shape, eye shape, nose shape, mouth shape, body pose, and composition. STYLE: Elegant linework with multi-step cel-shading, cinematic lighting effects, and atmospheric elements. Render existing features with anime aesthetic while maintaining realistic facial structure and perfect likeness. LIGHTING: Cinematic rim lights with atmospheric effects. COLOR: Rich filmic palette with warm skin tones. Keep the person 100% recognizable. Only apply anime rendering technique.' },
      { id: 'oil', name: 'Oil Painting', prompt: 'Apply classical oil painting rendering style. PRESERVE: Exact facial structure, face shape, all facial features, eye shape, nose shape, mouth shape, body pose, and composition. STYLE: Visible directional brushstrokes with rich layered pigments and canvas texture. Apply oil painting technique to existing features without altering facial geometry. TECHNIQUE: Impasto texture, wet-on-wet blending, warm and cool color temperatures. Keep the person 100% recognizable. Only change the rendering medium to oil painting technique while maintaining perfect facial likeness.' },
      { id: 'watercolor', name: 'Watercolor', prompt: 'Apply watercolor painting rendering style. PRESERVE: Exact facial structure, face shape, all facial features, eye shape, nose shape, mouth shape, body pose, and composition. STYLE: Transparent washes with soft edges, luminous translucent colors, and paper texture. Apply watercolor technique to existing features without altering facial geometry. TECHNIQUE: Color bleeding effects, loose fluid brushwork, preserved paper whites. Keep the person 100% recognizable. Only change the rendering medium to watercolor technique while maintaining perfect facial likeness.' },
      { id: 'sketch', name: 'Pencil Sketch', prompt: 'Apply graphite pencil sketch rendering style. PRESERVE: Exact facial structure, face shape, all facial features, eye shape, nose shape, mouth shape, body pose, and composition. STYLE: Varied pencil strokes with crosshatching and blending on textured paper. Apply pencil sketch technique to existing features without altering facial geometry. TECHNIQUE: Light to dark pencil range, paper texture, subtle smudging. Keep the person 100% recognizable. Only change the rendering medium to pencil sketch technique while maintaining perfect facial likeness.' },
      { id: 'comic', name: 'Comic Book', prompt: 'Apply comic book art rendering style. PRESERVE: Exact facial structure, face shape, all facial features, eye shape, nose shape, mouth shape, body pose, and composition. STYLE: Bold black ink outlines with vibrant flat color blocks and Ben-Day dot shading. Apply comic book technique to existing features without altering facial geometry. TECHNIQUE: Strong linework, limited color palette, solid shadows. Keep the person 100% recognizable. Only change the rendering style to comic book technique while maintaining perfect facial likeness.' },
      { id: 'lowpoly', name: 'Low Poly', prompt: 'Apply low-polygon 3D art rendering style. PRESERVE: Exact facial structure, face shape, all facial features, body pose, and composition. STYLE: Simple triangular polygonal facets with flat shading and geometric appearance. Apply low-poly technique to existing features without altering facial geometry or proportions. TECHNIQUE: Clear polygon edges, solid colors per face, minimal polygon count. Keep the person 100% recognizable. Only change the rendering style to low-poly 3D technique while maintaining perfect facial likeness.' },
      { id: 'ukiyo', name: 'Ukiyo-e', prompt: 'Apply traditional Japanese Ukiyo-e woodblock print rendering style. PRESERVE: Exact facial structure, face shape, all facial features, eye shape, nose shape, mouth shape, body pose, and composition. STYLE: Elegant flowing black outlines with limited flat color palette and traditional Japanese aesthetic. Apply Ukiyo-e technique to existing features without altering facial geometry. TECHNIQUE: Flat color blocks, paper grain texture, traditional pigments. Keep the person 100% recognizable. Only change the rendering style to woodblock print technique while maintaining perfect facial likeness.' },
      { id: 'impressionist', name: 'Impressionism', prompt: 'Apply Impressionist painting rendering style. PRESERVE: Exact facial structure, face shape, all facial features, eye shape, nose shape, mouth shape, body pose, and composition. STYLE: Short broken brushstrokes with vibrant colors and soft blurred edges emphasizing light effects. Apply Impressionist technique to existing features without altering facial geometry. TECHNIQUE: Layered strokes, optical color mixing, luminous quality. Keep the person 100% recognizable. Only change the rendering style to Impressionist painting technique while maintaining perfect facial likeness.' },
      { id: 'popart', name: 'Pop Art', prompt: 'Apply Pop Art rendering style. PRESERVE: Exact facial structure, face shape, all facial features, eye shape, nose shape, mouth shape, body pose, and composition. STYLE: Bright saturated colors with strong outlines, flat color blocks, and Ben-Day dot patterns. Apply Pop Art technique to existing features without altering facial geometry. TECHNIQUE: Limited bold palette, screen-printing appearance, high contrast. Keep the person 100% recognizable. Only change the rendering style to Pop Art technique while maintaining perfect facial likeness.' },
      { id: 'artdeco', name: 'Art Deco', prompt: 'Apply Art Deco rendering style. PRESERVE: Exact facial structure, face shape, all facial features, eye shape, nose shape, mouth shape, body pose, and composition. STYLE: Strong geometric patterns, bold clean lines, and sophisticated metallic color palette with luxurious aesthetic. Apply Art Deco technique to existing features without altering facial geometry. TECHNIQUE: Symmetrical designs, stylized decorative elements, glamorous opulent feel. Keep the person 100% recognizable. Only change the rendering style to Art Deco technique while maintaining perfect facial likeness.' },
    ],
  },
  {
    id: 'photo',
    name: 'Photo',
    icon: '📸',
    filters: [
      { id: 'vintage', name: 'Vintage Photo', prompt: 'Transform into authentic 1970s vintage photograph: COLOR GRADING - Warm, slightly faded tones with sepia or amber cast. Reduced saturation with emphasis on yellows, oranges, and browns. BLACKS - Lifted, faded blacks (not pure black). Gentle fade in shadow areas. GRAIN - Visible film grain texture throughout. Organic, analog quality. DAMAGE - Subtle aging effects: slight color shift, minor scratches or dust specks if appropriate. EXPOSURE - Slightly soft focus, gentle vignetting. QUALITY - Authentic film photography aesthetic from that era. AVOID - Digital clarity, pure whites/blacks, sharp modern look, HDR effects. AIM FOR - Nostalgic, warm film photography appearance with genuine aged photograph characteristics.' },
      { id: 'bw', name: 'Black & White', prompt: 'Convert to dramatic black and white photography (Ansel Adams style): CONTRAST - High contrast with rich tonal range. Deep, pure blacks and bright whites. MIDTONES - Full spectrum of grays with excellent tonal separation. TEXTURE - Enhanced texture detail and surface quality. Sharp, defined edges. LIGHTING - Dramatic lighting with strong shadows and highlights. Sculptural quality. COMPOSITION - Emphasize form, shape, and tonal relationships. QUALITY - Professional monochrome photography with excellent tonal depth. AVOID - Flat gray appearance, washed out tones, muddy midtones, sepia tinting. AIM FOR - Classic fine art black and white photography with dramatic impact and rich tonal depth.' },
      { id: 'hdr', name: 'HDR Look', prompt: 'Apply HDR (High Dynamic Range) photographic enhancement: DYNAMIC RANGE - Expanded tonal range with visible detail in both shadows and highlights. DETAILS - Enhanced micro-contrast and sharpness. Crisp, defined edges. COLORS - Boosted saturation with vibrant but believable colors. CLARITY - Increased local contrast for dramatic effect. SHADOWS - Lifted shadows with visible detail. HIGHLIGHTS - Controlled highlights preventing blowout. HALOS - Minimal haloing (avoid excessive glow around edges). DEPTH - Enhanced sense of dimension and pop. AVOID - Oversaturation, unrealistic appearance, excessive halos, cartoonish look. AIM FOR - Dramatic, impactful photography with enhanced realism and visual punch, professional HDR aesthetic.' },
      { id: 'cinematic', name: 'Cinematic', prompt: 'Apply professional cinematic color grading (Hollywood film aesthetic): COLOR PALETTE - Teal and orange color scheme (teal in shadows, warm orange in highlights and skin tones). CONTRAST - Controlled contrast with crushed blacks and gentle roll-off in highlights. MOOD - Atmospheric, moody feel with dramatic lighting. DEPTH - Enhanced dimensional quality through color separation. SHADOWS - Teal/cyan tint in shadow areas. SKIN TONES - Warm, flattering orange/peach tones. SATURATION - Selective saturation with emphasis on key colors. ASPECT - Wide cinematic framing aesthetic. AVOID - Flat colors, neutral grading, amateur video look, oversaturation. AIM FOR - Professional film look-up-table (LUT) quality grading like modern blockbuster movies.' },
      { id: 'softglow', name: 'Soft Glow', prompt: 'Apply soft romantic glow effect (portrait photography filter): GLOW - Gentle, diffused glow emanating from highlights. Soft halation effect. SKIN - Smoothed skin texture while maintaining natural appearance (not plastic). HIGHLIGHTS - Enhanced, luminous highlights with soft bloom. FOCUS - Slight softening overall with maintained subject clarity. MOOD - Dreamy, ethereal, flattering quality. COLORS - Slightly desaturated with warm, gentle tones. CONTRAST - Reduced contrast for soft, gentle appearance. AVOID - Harsh blur, loss of detail, over-smoothing, artificial look, excessive blur. AIM FOR - Professional portrait retouching aesthetic with flattering soft focus and romantic glow, elegant and natural.' },
      { id: 'filmnoir', name: 'Film Noir', prompt: 'Transform into classic Film Noir cinematography (1940s-50s detective film aesthetic): BLACK & WHITE - High contrast monochrome with dramatic tonal range. LIGHTING - Strong directional lighting with deep, dramatic shadows (chiaroscuro). Hard light creating sharp shadow edges. SHADOWS - Deep, inky blacks with bold shadow patterns. Venetian blind shadows, dramatic silhouettes. COMPOSITION - Low-key lighting, mysterious atmosphere, noir cinematography angles. MOOD - Dark, moody, mysterious, tension-filled atmosphere. CONTRAST - Extreme contrast between light and shadow areas. FOG/SMOKE - Atmospheric haze, volumetric lighting if appropriate. AVOID - Flat lighting, gray tones, bright cheerful mood, soft shadows. AIM FOR - Classic noir films like The Maltese Falcon or Double Indemnity with dramatic expressionist lighting and mystery.' },
      { id: 'doubleexposure', name: 'Double Exposure', prompt: 'Create artistic double exposure photography effect: TECHNIQUE - Blend two exposures together with translucent overlay. Primary subject with secondary ghostly image superimposed. TRANSPARENCY - Soft, ethereal transparency in overlapping areas. Multiple exposure blend. ELEMENTS - Combine subject with complementary imagery (nature, cityscapes, textures). BLENDING - Natural, organic blending modes (not cut-and-paste). Seamless integration. CONTRAST - Strong subject silhouette with lighter overlaid elements. MOOD - Dreamy, artistic, surreal quality. COMPOSITION - Thoughtful positioning of overlapping elements. AVOID - Harsh edges, obvious compositing, cluttered overlays, muddy blending. AIM FOR - Professional multiple exposure photography like analog double exposure technique with artistic, intentional overlapping imagery.' },
    ],
  },
  {
    id: 'trendy',
    name: 'Trendy',
    icon: '🔥',
    filters: [
      { id: 'cyber', name: 'Cyberpunk', prompt: 'Transform into cyberpunk aesthetic (Blade Runner, Ghost in the Shell style): LIGHTING - Bright neon lights in electric pink, cyan, purple, and blue. Strong color contrast. ATMOSPHERE - Dark, moody environment with luminous accents. Rain-slicked surfaces, fog, atmospheric haze. TECHNOLOGY - Futuristic tech elements, holographic displays, digital interfaces, circuitry patterns. COLORS - High saturation neon colors against dark backgrounds. Deep shadows with glowing highlights. MOOD - Dystopian urban environment, high-tech low-life aesthetic. EFFECTS - Light bloom, neon glow, reflections on wet surfaces. COMPOSITION - Urban night scene quality with dramatic lighting. AVOID - Bright daylight, natural colors, soft pastels, rural settings. AIM FOR - Dark futuristic cityscape aesthetic with neon-soaked cyberpunk atmosphere and technological dystopia feel.' },
      { id: 'vaporwave', name: 'Vaporwave', prompt: 'Transform into Vaporwave aesthetic (90s internet nostalgia art): COLORS - Pastel pink, cyan, purple, and magenta palette. Gradient backgrounds with color transitions. ELEMENTS - Retro 90s computer graphics, wireframe grids, Roman/Greek statues, palm trees, geometric shapes. EFFECTS - VHS glitch effects, scan lines, chromatic aberration, digital artifacts. MOOD - Dreamy, nostalgic, surreal, slightly melancholic atmosphere. COMPOSITION - Layered elements with depth, floating objects, impossible spaces. TYPOGRAPHY - Retro computer fonts if text present. AESTHETIC - Early internet, Windows 95, mall aesthetic, consumerism critique. AVOID - Modern clean design, realistic rendering, muted colors, sharp focus. AIM FOR - Nostalgic internet aesthetic with dreamy surrealism and retro digital collage feel.' },
      { id: 'pixel', name: 'Pixel Art', prompt: 'Convert into authentic 8-bit/16-bit pixel art (retro video game style): PIXELS - Clearly visible square pixels at low resolution. Crisp pixel edges (no anti-aliasing). PALETTE - Limited color palette (16-64 colors maximum). Consistent indexed color scheme. SIMPLIFICATION - Reduce forms to essential shapes readable at low resolution. SHADING - Dithering patterns for gradients, limited color ramps. STYLE - Classic video game sprite aesthetic (NES, SNES, Game Boy era). OUTLINES - Dark outlines defining shapes. DETAIL - Strategic detail placement within pixel constraints. AVOID - Smooth gradients, photo-realistic detail, modern high-resolution look, blur effects. AIM FOR - Authentic retro video game pixel art with charm and readability of classic 8-bit or 16-bit games.' },
      { id: 'vhs', name: 'Retro VHS', prompt: 'Transform into retro VHS tape recording aesthetic (1980s-90s home video): DISTORTION - Horizontal scan lines, tracking errors, image warping, magnetic tape artifacts. COLOR SHIFT - Color bleeding, especially pinks and cyans. Chromatic separation. QUALITY - Low resolution, analog video compression, reduced sharpness. NOISE - Video noise, static, analog grain throughout. TIMESTAMP - Digital timestamp in corner (optional). Retro camcorder date/time overlay. EFFECTS - Occasional glitches, dropout, magnetic interference. MOOD - Nostalgic, lo-fi, home video memories aesthetic. AVOID - Digital clarity, HD quality, modern video codecs, clean image. AIM FOR - Authentic degraded VHS tape quality with analog video artifacts and 80s/90s home video camcorder feel.' },
      { id: 'graffiti', name: 'Street Art', prompt: 'Transform into vibrant street art/graffiti style (urban mural aesthetic): TECHNIQUE - Spray paint textures with drips, overspray, and stencil effects. COLORS - Bold, vibrant colors with high saturation. Multiple layered colors. STYLE - Wildstyle letters, characters, or illustrative elements. Urban art vocabulary. SURFACE - Brick wall, concrete, or urban surface texture visible. DETAILS - Paint drips, caps spray patterns, tape edges, stencil boundaries. COMPOSITION - Dynamic, energetic, rebellious aesthetic. Layered imagery. MOOD - Raw, expressive, urban street culture. EFFECTS - Overspray halos, color blending, weathering if appropriate. AVOID - Clean digital look, precise edges, corporate aesthetic, watercolor softness. AIM FOR - Authentic street art aesthetic with spray paint authenticity and urban mural energy like Banksy or traditional graffiti artists.' },
      { id: 'isometric', name: 'Isometric Art', prompt: 'Transform into isometric 3D art (technical illustration style): PERSPECTIVE - True isometric projection (30° angles, no perspective distortion). All parallel lines remain parallel. GEOMETRY - Clean geometric forms with precise angles. Cubic/rectangular construction. STYLE - Flat shaded surfaces with clear facets. Architectural/technical quality. COLORS - Solid, distinct colors per face. Clear color separation for each surface. EDGES - Sharp, clean edges. Precise line work. AESTHETIC - Video game isometric view, technical diagram quality. DETAILS - Small elements in isometric perspective. Grid-based placement. SHADING - Flat or simple 3-tone shading per surface. AVOID - Perspective distortion, curved lines, photo-realism, atmospheric effects. AIM FOR - Clean isometric technical illustration like Monument Valley game or architectural diagrams with precise geometric clarity.' },
      { id: 'gta', name: 'GTA Style', prompt: 'Transform into iconic Grand Theft Auto game cover art illustration style while preserving exact facial features and identity. SIGNATURE GTA LOOK - Rockstar Games distinctive illustrated realism: hyper-stylized digital painting with bold graphic novel elements. Reference GTA V, San Andreas, Vice City loading screens and cover art aesthetic. LINEWORK - Thick confident black ink outlines around ALL major forms (face, hair, clothing, body). Comic book border lines 3-4px thick. Strong contour lines defining facial planes, jawline, cheekbones. Graphic novel quality borders. SHADING TECHNIQUE - Hard-edged cel-shading with NO soft transitions. 4-5 distinct tonal zones per color area. Deep shadow areas in rich purples, dark blues, or near-black. Mid-tones in saturated base colors. Highlights in warm oranges, yellows, or hot pinks. Airbrush-smooth within each zone but SHARP edges between zones. COLOR GRADING - Extreme saturation boost (+40%). Shadows tinted with deep purple/blue (never pure black). Skin tones pushed toward warm orange/amber. Complementary color contrast (warm vs cool). Vibrant urban palette: hot pinks, electric blues, neon greens, deep purples, golden yellows. LIGHTING - Dramatic low-angle or side lighting like action movie posters. Strong rim lighting creating glowing edges (often in contrasting colors - blue rim on warm subject). Multiple colored light sources (street lights, neon signs). Cinematic lens flare or light streaks. TEXTURE - Smooth digital airbrush finish with subtle halftone dot pattern (like screen printing). NO photo grain. Clean vector-like quality with painted details. FACIAL RENDERING - Sculpted planes with defined cheekbones, strong jawline emphasis. Eyes with sharp white highlights (catchlights). Lips with 2-3 tone rendering. Nose with clear light/shadow definition. Hair rendered in chunky graphic shapes with highlights. ATMOSPHERE - Urban gritty street culture energy. Confident swagger and attitude in expression. Badass action hero presence. Movie poster drama. COMPOSITION - Bold frontal or 3/4 view. Strong eye contact. Dynamic presence filling frame. Magazine cover quality. EFFECTS - Optional: subtle lens flare, light rays, atmospheric glow, neon reflections, urban haze. PRESERVE - Exact face shape, bone structure, eye shape, nose, mouth, all facial proportions. 100% recognizable identity. AVOID - Soft painterly look, photorealism, flat colors, anime style, watercolor, sketchy lines, muted colors, natural lighting. AIM FOR - Unmistakable Rockstar Games GTA cover art: bold, graphic, saturated, dramatic, with thick outlines and hard-edged shading. Street art meets digital illustration meets action movie poster.' },
    ],
  },
  {
    id: 'seasonal',
    name: 'Seasonal',
    icon: '🎄',
    filters: [
      { id: 'christmas', name: 'Christmas', prompt: 'Transform into festive Christmas scene while preserving exact facial features and identity. Add holiday elements around subject: Cozy winter sweaters, Santa hats, scarves, festive accessories. Decorate background with Christmas trees, twinkling lights, ornaments, wreaths, garland, presents. Rich holiday colors (red, green, gold, white). Warm glowing lighting from fairy lights and candles. Soft falling snow or bokeh light effects. Festive cheerful atmosphere. Keep face shape, nose, eyes, mouth identical.' },
      { id: 'halloween', name: 'Halloween', prompt: 'Apply festive autumn Halloween styling while preserving exact facial features and identity. Add fun costume accessories and festive elements. Decorate scene with carved pumpkins, autumn leaves, orange and purple decorations. Warm orange and purple color palette. Soft glowing candlelight effect. Mysterious evening atmosphere with gentle fog. Festive autumn celebration mood. Family-friendly holiday aesthetic. Keep face shape, nose, eyes, mouth identical.' },
      { id: 'valentines', name: "Valentine's Day", prompt: 'Transform into romantic Valentine\'s scene while preserving exact facial features and identity. Add romantic elements around subject: Soft romantic styling, hearts, roses, cupid motifs. Decorate background with rose petals, heart decorations, romantic candles, soft fabrics. Romantic color palette (reds, pinks, whites, soft purples). Soft dreamy lighting with romantic glow. Bokeh heart-shaped lights. Sweet romantic atmosphere. Keep face shape, nose, eyes, mouth identical.' },
      { id: 'easter', name: 'Easter', prompt: 'Transform into cheerful Easter scene while preserving exact facial features and identity. Add spring elements around subject: Pastel spring clothing, bunny ears, floral accessories, Easter bonnets. Decorate background with Easter eggs, spring flowers, bunnies, baskets, blooming gardens. Soft pastel palette (pink, lavender, mint, yellow, baby blue). Bright cheerful spring lighting. Fresh spring atmosphere. Keep face shape, nose, eyes, mouth identical.' },
      { id: 'newyear', name: 'New Year', prompt: 'Transform into celebratory New Year scene while preserving exact facial features and identity. Add party elements around subject: Glamorous party attire, party hats, festive accessories, champagne glasses. Decorate background with confetti, balloons, streamers, fireworks, clocks showing midnight, sparklers. Metallic colors (gold, silver, black, white). Dramatic celebratory lighting with sparkles and glitter effects. Festive party atmosphere. Keep face shape, nose, eyes, mouth identical.' },
      { id: 'summer', name: 'Summer Vibes', prompt: 'Transform into bright summer scene while preserving exact facial features and identity. Add summer elements around subject: Light summer clothing, sunglasses, beach accessories, tropical prints. Decorate background with palm trees, beach elements, tropical flowers, sunshine, blue skies. Bright vibrant summer colors (turquoise, coral, yellow, tropical greens). Bright sunny lighting with lens flares. Warm tropical vacation atmosphere. Keep face shape, nose, eyes, mouth identical.' },
      { id: 'winter', name: 'Winter Wonderland', prompt: 'Transform into magical winter scene while preserving exact facial features and identity. Add winter elements around subject: Cozy winter clothing, knit sweaters, scarves, beanies, mittens. Decorate background with snow, snowflakes, icicles, frosted trees, winter landscapes. Cool winter palette (icy blue, white, silver, soft purple). Soft diffused winter lighting with sparkly snow effects. Peaceful snowy atmosphere. Keep face shape, nose, eyes, mouth identical.' },
    ],
  },
  {
    id: 'fun',
    name: 'Fun & Creative',
    icon: '🎭',
    filters: [
      { id: 'cartoon', name: '3D Cartoon', prompt: 'Apply 3D animated film rendering style (DreamWorks/Illumination aesthetic). PRESERVE: Exact facial structure, face shape, eye placement, nose shape, mouth shape, all facial proportions, body pose, and composition. STYLE: Smooth 3D rendering with clean painted textures, soft lighting, and vibrant colors. Render existing features in 3D animation style while maintaining perfect facial likeness and proportions. Keep the person 100% recognizable. Only apply 3D animation rendering technique to existing structure without altering facial geometry.' },
      { id: 'pixar', name: 'Pixar Style', prompt: 'Apply Pixar Animation Studios rendering style. PRESERVE: Exact facial structure, face shape, eye shape and placement, nose shape, mouth shape, all facial proportions, body pose, and composition. STYLE: Smooth stylized 3D rendering with warm cinematic lighting, clean textures, and rich colors. Render existing features in Pixar aesthetic while maintaining perfect facial likeness. Keep the person 100% recognizable with their unique facial characteristics intact. Only apply Pixar rendering technique to existing structure without altering facial geometry or proportions.' },
      { id: 'caricature', name: 'Caricature', prompt: 'Apply playful caricature illustration style while preserving identity. PRESERVE: Core facial identity and recognizability. STYLE: Slightly exaggerated features in a fun, artistic way with bold lines and expressive rendering. The person should still be clearly recognizable but with a playful, illustrated quality. Warm colors, dynamic poses, professional caricature artist quality.' },
      { id: 'claymation', name: 'Claymation', prompt: 'Apply stop-motion claymation rendering style (Aardman/Laika aesthetic). PRESERVE: Exact facial structure, all facial features, body pose, and composition. STYLE: Smooth clay-like texture with visible fingerprint impressions, matte finish, soft studio lighting. Render as if the person is a detailed clay sculpture photographed in stop-motion style. Keep the person 100% recognizable.' },
      { id: 'lego', name: 'LEGO Style', prompt: 'Transform into LEGO minifigure style while preserving identity. PRESERVE: Overall likeness and recognizable features. STYLE: Blocky LEGO aesthetic with plastic texture, simple geometric shapes, bright colors. Render as if the person is a custom LEGO minifigure. Maintain recognizable characteristics like hair color, skin tone, and key features.' },
      { id: 'funko', name: 'Funko Pop', prompt: 'Transform into Funko Pop vinyl figure style. PRESERVE: Key identifying features and likeness. STYLE: Large oversized head, small body, big round black eyes, simplified features, glossy vinyl texture. Render as a collectible Funko Pop figure while maintaining recognizable characteristics like hair style, hair color, and clothing.' },
    ],
  },
  {
    id: 'aesthetic',
    name: 'Aesthetic',
    icon: '🌸',
    filters: [
      { id: 'cottagecore', name: 'Cottagecore', prompt: 'Apply cottagecore aesthetic styling while preserving exact facial features and identity. Add soft, dreamy pastoral elements: flower crowns, linen textures, soft golden hour lighting, meadow backgrounds with wildflowers. Warm, muted earth tones with soft pink and cream accents. Romantic, whimsical countryside atmosphere. Keep face shape, nose, eyes, mouth identical.' },
      { id: 'darkacademia', name: 'Dark Academia', prompt: 'Apply dark academia aesthetic styling while preserving exact facial features and identity. Add scholarly elements: tweed textures, leather-bound books, vintage library settings, warm amber lighting. Rich browns, deep greens, burgundy, and cream color palette. Intellectual, moody, romantic atmosphere with vintage academic feel. Keep face shape, nose, eyes, mouth identical.' },
      { id: 'lightacademia', name: 'Light Academia', prompt: 'Apply light academia aesthetic styling while preserving exact facial features and identity. Add bright scholarly elements: cream linens, marble textures, sunlit library or museum settings. Soft whites, beiges, light browns, and gold accents. Airy, intellectual, classical atmosphere with Greek/Roman influences. Keep face shape, nose, eyes, mouth identical.' },
      { id: 'softgirl', name: 'Soft Girl', prompt: 'Apply soft girl aesthetic styling while preserving exact facial features and identity. Add cute, youthful elements: pastel colors (pink, lavender, baby blue), cloud motifs, soft blush makeup effect, dreamy lighting. Gentle, feminine, sweet atmosphere with soft focus effect. Keep face shape, nose, eyes, mouth identical.' },
      { id: 'grunge', name: '90s Grunge', prompt: 'Apply 90s grunge aesthetic styling while preserving exact facial features and identity. Add grunge elements: flannel textures, ripped denim, band t-shirts, doc martens. Desaturated, moody color palette with deep reds, forest greens, and black. Gritty urban backdrop with vintage film grain effect. Keep face shape, nose, eyes, mouth identical.' },
      { id: 'minimalist', name: 'Clean Minimalist', prompt: 'Apply minimalist aesthetic styling while preserving exact facial features and identity. Clean, simple composition with plenty of negative space. Neutral color palette: whites, grays, beige, black. Modern, sophisticated, uncluttered atmosphere. Soft, even lighting with no harsh shadows. Scandinavian design influence. Keep face shape, nose, eyes, mouth identical.' },
      { id: 'royalcore', name: 'Royalcore', prompt: 'Apply royalcore aesthetic styling while preserving exact facial features and identity. Add regal elements: velvet textures, gold accents, crown motifs, palace backgrounds. Rich jewel tones: deep purple, emerald, ruby red, gold. Luxurious, elegant, royal atmosphere with dramatic lighting. Keep face shape, nose, eyes, mouth identical.' },
    ],
  },
  {
    id: 'portrait',
    name: 'Portrait',
    icon: '🖼️',
    filters: [
      { id: 'pinup', name: 'Pin-Up Art', prompt: 'Transform into classic 1950s pin-up illustration style while preserving exact pose, composition, and facial features. CRITICAL: Maintain original body position, pose, and framing exactly as shown. Vintage illustration aesthetic with painted quality and soft airbrushed look. Retro styling with period-appropriate hair and makeup. Warm vintage color palette with soft pastels and bold reds. Confident, playful expression with classic pin-up charm. Alberto Vargas or Gil Elvgren artistic quality with painted illustration technique. Nostalgic 1950s calendar art aesthetic. Keep original pose, body position, face shape, nose, eyes, mouth identical.' },
      { id: 'renaissance', name: 'Renaissance', prompt: 'Transform into Renaissance master painting style while preserving exact pose, composition, and facial features. CRITICAL: Maintain original body position, pose, and framing exactly as shown. Classical oil painting technique with rich colors and dramatic lighting. Elegant period styling with Renaissance aesthetic. Warm golden lighting with chiaroscuro shadows. Luxurious fabrics like velvet and silk in deep jewel tones. Dignified, serene expression. Old master painting quality like Titian or Raphael with classical beauty ideals. Timeless artistic portrait. Keep original pose, body position, face shape, nose, eyes, mouth identical.' },
      { id: 'baroque', name: 'Baroque', prompt: 'Transform into Baroque painting style while preserving exact pose, composition, and facial features. CRITICAL: Maintain original body position, pose, and framing exactly as shown. Dramatic lighting with strong contrasts and rich colors. Opulent styling with luxurious fabrics and ornate details. Deep shadows and golden highlights. Confident, regal expression. Rembrandt or Caravaggio quality with theatrical lighting and rich textures. Grand, dramatic aesthetic. Keep original pose, body position, face shape, nose, eyes, mouth identical.' },
      { id: 'rococo', name: 'Rococo', prompt: 'Transform into Rococo painting style while preserving exact pose, composition, and facial features. CRITICAL: Maintain original body position, pose, and framing exactly as shown. Soft, delicate aesthetic with pastel colors and ornate details. Elegant styling with ribbons, lace, and flowing fabrics. Gentle lighting with soft shadows. Sweet, charming expression. François Boucher or Jean-Honoré Fragonard quality with romantic, decorative style. Playful, lighthearted atmosphere. Keep original pose, body position, face shape, nose, eyes, mouth identical.' },
      { id: 'noir', name: 'Noir Portrait', prompt: 'Transform into film noir portrait style while preserving exact pose, composition, and facial features. CRITICAL: Maintain original body position, pose, and framing exactly as shown. Dramatic black and white with strong shadows and highlights. Sophisticated styling with elegant attire and classic beauty. Hard directional lighting creating mystery. Confident, enigmatic expression. Classic Hollywood portrait quality with dramatic chiaroscuro. Timeless, sophisticated aesthetic. Keep original pose, body position, face shape, nose, eyes, mouth identical.' },
      { id: 'glamour', name: 'Glamour', prompt: 'Apply high-fashion glamour photography styling while preserving exact pose, composition, and facial features. CRITICAL: Maintain original body position, pose, and framing exactly as shown. Professional fashion editorial aesthetic with dramatic makeup and styled hair. Flattering studio lighting with soft key light and rim lighting. Enhance wardrobe with elegant fabrics while keeping original clothing style. Rich colors with skin tone perfection. Confident, empowered expression. Vogue editorial quality with professional retouching and natural beauty enhancement. High-end fashion magazine aesthetic. Keep original pose, body position, face shape, nose, eyes, mouth identical.' },
      { id: 'studio', name: 'Studio Portrait', prompt: 'Transform into professional studio portrait while preserving exact pose, composition, and facial features. CRITICAL: Maintain original body position, pose, and framing exactly as shown. Professional lighting setup with key light, fill light, and rim light. Flawless styling with elegant wardrobe and professional hair and makeup. Clean background with gradient. Confident, engaging expression. High-end fashion photography quality with perfect lighting and retouching. Polished, professional aesthetic. Keep original pose, body position, face shape, nose, eyes, mouth identical.' },
      { id: 'western', name: 'Western Theme', prompt: 'Reimagine in classic American Old West aesthetic with authentic frontier atmosphere. Apply rugged cowboy styling with weathered textures, cowboy hats, boots, leather elements, vests, bandanas, and duster coats. Create a dusty frontier setting with wooden buildings, hitching posts, tumbleweeds, and vast open skies. Use warm golden hour lighting with dramatic shadows and atmospheric dust. Apply sepia-toned or desaturated color palette with browns, oranges, and muted earth tones. Include authentic western details like horses, cattle, cacti, and weathered wood textures for immersive Wild West atmosphere.' },
    ],
  },
];

// Helper to get all filters as a flat array
export const getAllStyleFilters = (): StyleFilter[] => {
  return STYLE_FILTER_CATEGORIES.flatMap(cat => cat.filters);
};

// Helper to find a filter by ID
export const getStyleFilterById = (id: string): StyleFilter | undefined => {
  return getAllStyleFilters().find(f => f.id === id);
};
